[profile.default]
src = "src"
out = "out"
libs = ["lib"]
cache_path  = "forge-cache"
solc-version = "0.8.30"
evm_version = "prague"
via_ir = true
optimizer = true
optimizer-runs = 2000

rpc_endpoints = { mainnet = "https://eth.drpc.org", sepolia = "https://rpc.ankr.com/eth_sepolia", base = "https://mainnet.base.org" }
